use_frameworks!

target 'AKQQManager_Example' do
  pod 'AKQQManager', :path => '../'
  
  #pod 'AKQQSDK', :git => 'git@github.com:ArtisanKid/AKQQSDK.git'
  pod 'AKQQSDK', :path => '../../AKQQSDK'
  
  pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      def installer.verify_no_static_framework_transitive_dependencies; end
  end

  target 'AKQQManager_Tests' do
    inherit! :search_paths

    
  end
end
